// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVqR6reKbgPvYRvYtNxE1Om6wgZJ5NpbM',
    appId: '1:883048527937:web:6e312574b8c45beaa0aec0',
    messagingSenderId: '883048527937',
    projectId: 'otpproject-8046d',
    authDomain: 'otpproject-8046d.firebaseapp.com',
    databaseURL: 'https://otpproject-8046d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'otpproject-8046d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_TvU2Bh2YxOthjRVzPf_0FBg8Azf3WA4',
    appId: '1:883048527937:android:39c3559ccf996c79a0aec0',
    messagingSenderId: '883048527937',
    projectId: 'otpproject-8046d',
    databaseURL: 'https://otpproject-8046d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'otpproject-8046d.appspot.com',
  );
}
